### PR TITLE
[flink-job] Expose flinkVersion field

### PR DESCRIPTION
**Pull request by pjthepooh**
Adding this field for Spotify flink operator we recently switched over to in https://github.com/Nextdoor/k8s/pull/508

### CODE REVIEW

**Review by sabw8217 — APPROVED** [review]
we confirmed there aren't any other setting we need to add?

**Review by diranged — CHANGES_REQUESTED** [review]
Please don’t set the default value to 1.13.1 … instead, leave the value string empty in the values.yaml file.

**Comment by pjthepooh** [comment]
> we confirmed there aren't any other setting we need to add?

cpu limit as well, but can be handled in app level

We may want to expose `Status` field too (i need to read up how to use it), but lets do it in another PR and later.

**Comment by diranged** [comment]
> > we confirmed there aren't any other setting we need to add?
> 
> cpu limit as well, but can be handled in app level
> 
> We may want to expose `Status` field too (i need to read up how to use it), but lets do it in another PR and later.

The status field is read-only  - its filled in by the operator, not by us.. so nothing to do here in the chart for that.

**Review by diranged — APPROVED** [review]

**Pull request merged**
